### ISSUE TITLE
How to synthesis a wav file.

### ISSUE THREAD

**Issue by mudong0419** [mutiann/few-shot-transformer-tts#2]
It's a great news that you release your pretrained models.
I have download checkpoints, and json files. How to synthesis a wav file, given a text and language? Specially in the case of code-switched text, like "Hello, 我是AI助手，很高兴认识你, nice to meet you."
Thanks in advance.

**Comment by mutiann** [comment]
I've just updated the code and README to explain the synthesis part. However since the model is not designed for code-switched text as it uses a global language ID, it is not really reliable in the scenario. Nevertheless, it actually works to an extent, if you use the metadata with code-switched texts like `databaker_cs|500|很高兴认识你, nice to meet you|zh-cn`.

**Comment by mudong0419** [comment]
Many thanks for your advice. It's so cool that code-switched voice is very fluent. But in the case ljspeech_0|500|Alphabet is A B C D E F G H I J K L M N O P Q R S T U V W X Y Z.|en-us, single character is not pronouncing very well, should I replace a character with its phoneme? Look forward your suggestions.

**Comment by mutiann** [comment]
It is a well-known issue in neural TTS that on such ill-formed sentences far from the training domain (like those with consecutive letters, numbers, etc.), typical seq2seq model will often fail, even it is using phoneme inputs. You can have a try by changing letters to longer texts (A, Bee, See, Dee, etc.), which may help. But if you really want to ensure that it is reliable, methods specially designed for the scenario (such as Tacotron2+Stepwise Monotonic Attention or FastSpeech) are recommended.

**Comment by mudong0419** [comment]
Thank you so much. I'll have a try.
