### ISSUE TITLE
quick question:confirmation of procedure to utilize and run project

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [mutiann/few-shot-transformer-tts#9]
I had a some samples of japanese voice which i want to adapt to this tts.probably around 5-10minute

i had downloaded the t3 pretrained model
next step should be download the repo and unpack.
then run:pip install -r requirement.txt
then run:python -m torch.distributed.launch --nproc_per_node=NGPU train.py --model-dir=MODEL_DIR --log-dir=LOG_DIR --data-dir=DATA_DIR --training_languages=en-us:de-de:fr-fr:ru-ru:en-uk:es-es:uk-ua:pl-pl:it-it:ja-jp:zh-cn:nl-nl:fi-fi: ko-kr:eu-es:pt-br:hu-hu:jv-id:gl-es:gu-in:kn-in:da-dk:su-id:ta-in:ca-es:ml-in:te-in:my-mm:yo-ng:km-kh:mr-in:ne-np: bn-bd:bn-in:si-lk --adapt_languages=ja-jp --downsample_languages=ja-jp:100 --ddp=True --hparams="warmup_steps=800000" --restore_from=MODEL_DIR/model.ckpt-700000

how should the data-dir folder layout be?

where should i put my obtained voice sample?is it in data-dir?

I assume all my voice sample need to be re-encoded to mono,wav,22.05kHz,right?

**Comment by mutiann** [comment]
Hello. To adapt your own dataset to the pipeline, you need to arrange the data like
- transformed_path # As defined in corpora/__init__.py
   - YOUR_DATASET_NAME
      - wavs
         - SPEAKER_NAME_000000.wav
         - SPEAKER_NAME_000001.wav
         - ...
      - metadata.csv

Waveforms are in mono and 16kHz.

While the metadata.csv is like
```
SPEAKER_NAME_000000|トランスクリプトの例|SPEAKER_NAME|ja-jp
SPEAKER_NAME_000001|別のトランスクリプトの例|SPEAKER_NAME|ja-jp
...
```

There are codes in corpora/ to transform other datasets to the form above, which could be used for your reference.

It is OK to train using only your dataset, but since your dataset is really small, it is preferred to co-train with other datasets, or at least other Japanese datasets. In this case you need to follow the instructions in README to prepare the Japanese datasets (i.e. JSUT and the ja-jp part of CSS-10).

Then you need to add the name of your dataset and its language to `include_corpus` and `dataset_language`, and next run corpora/process_corpus.py, which will produce the final data_dir.

One thing needs to be noticed is that process_corpus.py will do some filtering and dispose data considered not good. Particularly, it will dispose speakers with less than 100 samples. It might be necessary for you to modify the code to disable the filtering. Also, for a small dataset of a new speaker, it might be beneficial to balance not the languages but the speakers. It is esay to implement by modifying _group_meta in dataloader.py.

--downsample_languages=ja-jp:100 will randomly select only 100 samples in ja-jp for training, so in your case it might not be a good idea. Also you only need to include languages that you are really using into the argument --training_languages.

**Comment by RESDXChgfore9hing** [comment]
huge thanks.will try and see if i can adapt it.
